import { Instrument } from './types';

export const INSTRUMENTS: Instrument[] = [
  {
    symbol: 'AAVE/USD.crypto',
    name: 'Aave vs US Dollar',
    assetType: 'Foreign Exchange',
    currency: 'USD',
    precision: 0.01,
    marginRate: '50%',
    lotSize: 1.0,
    minSize: 0.1,
    maxSize: 500.0,
    stepSize: 0.1,
  },
  {
    symbol: 'ADA/USD.crypto',
    name: 'Cardano vs US Dollar',
    assetType: 'Foreign Exchange',
    currency: 'USD',
    precision: 0.0001,
    marginRate: '50%',
    lotSize: 1.0,
    minSize: 10.0,
    maxSize: 50000.0,
    stepSize: 10.0,
  },
  {
    symbol: 'AVAX/USD.crypto',
    name: 'Avalanche vs US Dollar',
    assetType: 'Foreign Exchange',
    currency: 'USD',
    precision: 0.001,
    marginRate: '50%',
    lotSize: 1.0,
    minSize: 0.1,
    maxSize: 2000.0,
    stepSize: 0.1,
  },
  {
    symbol: 'BTC/USD.crypto',
    name: 'Bitcoin vs US Dollar',
    assetType: 'Foreign Exchange',
    currency: 'USD',
    precision: 0.1,
    marginRate: '20%',
    lotSize: 1.0,
    minSize: 0.00001,
    maxSize: 20.0,
    stepSize: 0.00001,
  },
  {
    symbol: 'ETH/USD.crypto',
    name: 'Ethereum vs US Dollar',
    assetType: 'Foreign Exchange',
    currency: 'USD',
    precision: 0.01,
    marginRate: '20%',
    lotSize: 1.0,
    minSize: 0.0001,
    maxSize: 200.0,
    stepSize: 0.0001,
  },
  {
    symbol: 'LINK/USD.crypto',
    name: 'Chainlink vs US Dollar',
    assetType: 'Foreign Exchange',
    currency: 'USD',
    precision: 0.001,
    marginRate: '50%',
    lotSize: 1.0,
    minSize: 0.1,
    maxSize: 5000.0,
    stepSize: 0.1,
  },
  {
    symbol: 'SOL/USD.crypto',
    name: 'Solana vs US Dollar',
    assetType: 'Foreign Exchange',
    currency: 'USD',
    precision: 0.01,
    marginRate: '50%',
    lotSize: 1.0,
    minSize: 0.01,
    maxSize: 5000.0, // Assumed from pattern, image cut off but shows ,000.00
    stepSize: 0.01,
  },
];
